### PR TITLE
Erasing Functionality (Feature)

### PR DESCRIPTION
**Pull request by emmanuelmuturia**
- Created a feature branch for the Erase functionality...

### CODE REVIEW

**Review by Fbada006 — CHANGES_REQUESTED** [review]
Hey @emmanuelmuturia , it seems there has been a breakdown. The feature branch is only merged to main once it is complete. The changes you want to merge to main here are not complete, therefore, main will be essentially broken. Once you create a feature branch, you create branches off of the feature branch, then open pull requests against the feature branch. Once you have completed the entire feature, then merge the feature branch back to main. In this example, I expect you to create a branch say called `emmanuelmuturia/task/add-rubbing-functionality` where its base branch is `feature/erasing-functionality`, then open a pr from the former to the latter, and so on until the feature is complete.

**Comment by emmanuelmuturia** [comment]
@Fbada006 This is noted. What about these two PRs that are already open?

**Comment by CalebKL** [comment]
@emmanuelmuturia one more thing, please mark this PR as a draft PR because its incomplete, as soon as you complete working on the changes, you can make it open and request a review.

**Comment by Fbada006** [comment]
> @Fbada006 This is noted. I have already merged the task branch to this feature branch...

Yes, but you are still trying to merge incomplete changes to master. That should not be done. The flow goes like this, create a feature branch from main, then publish the feature branch. From the feature branch, create a branch for a small task, then open a PR to merge back to the feature branch. This continues until you finish the feature branch, then open a pr from the feature to main. As it is, these changes cannot make it back to main because the feature is not even half complete.

**Comment by emmanuelmuturia** [comment]
@CalebKL and @Fbada006 I have converted the branch to a draft branch. Will that suffice or will I have to redo the entire process of creating the feature branch and its subsequent task branches?

**Pull request closed without merging**
