### PR TITLE
Release 2.3.0

### LINKED ISSUE #117: Refine The Release Pipeline
`releaseArtMaker.sh` needs a bit of refinement as it occasionally fails to register multiple Release Notes as well as format them correctly...

### PR DESCRIPTION
**Pull request by emmanuelmuturia**
This PR documents the publishing of Release 2.3.0 and it also fixes #117 by adding some refinements to `releaseArtMaker.sh` and `RELEASE.md`...

### CODE REVIEW

**Comment by Fbada006** [comment]
Is this tested @emmanuelmuturia ? If so, where?

**Comment by emmanuelmuturia** [comment]
> Is this tested @emmanuelmuturia ? If so, where?

Here is a sample GitHub Release that I have created right now to confirm that it works as expected: https://github.com/Fbada006/ArtMaker/releases/tag/untagged-307411caaa1098f34ba0

I had deleted the previous ones and forgot to leave the latest one after testing. As for Release 2.3.0, I ensured that the Publish Pipeline ran successfully but the changes have not yet been reflected on Maven Central...

**Comment by Fbada006** [comment]
@emmanuelmuturia , your release cannot go through because the release version has not been updated in the scripts as explained in the release read me file. The version still points to 2.2.0 instead of 2.3.0. As much as you updated the read me to have the instructions for using your github release script, the previous instructions still apply.

**Comment by emmanuelmuturia** [comment]
> @emmanuelmuturia , your release cannot go through because the release version has not been updated in the scripts as explained in the release read me file. The version still points to 2.2.0 instead of 2.3.0. As much as you updated the read me to have the instructions for using your github release script, the previous instructions still apply.



> @emmanuelmuturia , your release cannot go through because the release version has not been updated in the scripts as explained in the release read me file. The version still points to 2.2.0 instead of 2.3.0. As much as you updated the read me to have the instructions for using your github release script, the previous instructions still apply.

I had incremented `libVersion` before pushing the changes and triggering `publish.yml` as seen here: https://github.com/Fbada006/ArtMaker/blob/release/2.3.0/scripts/publish.gradle.kts

I have modified the instructions to include this. Please let me know if there is something else that I may have not considered...

**Comment by Fbada006** [comment]
This is okay. I had to re-trigger the release pipeline. I will look at the script in detail later.

**Review by Fbada006 — APPROVED** [review]

**Pull request merged**
