### PR TITLE
Toggle Eraser Button Based On Drawing Presence

### LINKED ISSUE #89: The rubbing button should not be enabled if there is no drawing
As it is, the rubbing button is enabled regardless of whether there is a shape on screen or not. We need to add logic to conditionally enable or disable the rubbing button the same way we have enabled or disabled the undo, redo, and clear functionality.

### PR DESCRIPTION
**Pull request by emmanuelmuturia**
- Fixes #89 by toggling the Eraser Button based on Drawing presence...

### CODE REVIEW

**Comment by emmanuelmuturia** [comment]
@Fbada006 @CalebKL I could use some help. In `ArtMaker.kt` from line 83 to 87 I try to dynamically toggle the Eraser once `state.canErase` switches to false but the app crashes just after it works. Please look into this and le time know how this could be fixed. Here is the referenced snippet:

`LaunchedEffect(key1 = state.canErase) {
        if (!state.canErase) {
            isEraserActive = false
        }
    }`

**Comment by CalebKL** [comment]
> @Fbada006 @CalebKL I could use some help. In `ArtMaker.kt` from line 83 to 87 I try to dynamically toggle the Eraser once `state.canErase` switches to false but the app crashes just after it works. Please look into this and let me know how this could be fixed. Here is the referenced snippet and Stacktrace respectively:
> 
> `LaunchedEffect(key1 = state.canErase) { if (!state.canErase) { isEraserActive = false } }`
> 
> ```
> `JNI DETECTED ERROR IN APPLICATION: JNI CallVoidMethodV called with pending exception java.lang.IndexOutOfBoundsException: index: -1, size: 0
>                                                                                                 java_vm_ext.cc:591]   at void androidx.compose.runtime.external.kotlinx.collections.immutable.internal.ListImplementation.checkElementIndex$runtime_release(int, int) (ListImplementation.kt:15)
>                                                                                                 java_vm_ext.cc:591]   at java.lang.Object androidx.compose.runtime.external.kotlinx.collections.immutable.implementations.immutableList.SmallPersistentVector.get(int) (SmallPersistentVector.kt:146)
>                                                                                                 java_vm_ext.cc:591]   at java.lang.Object androidx.compose.runtime.snapshots.SnapshotStateList.get(int) (SnapshotStateList.kt:100)
>                                                                                                 java_vm_ext.cc:591]   at void io.artmaker.export.DrawingManager.updateCurrentShape-3MmeM6k(long, float) (DrawingManager.kt:76)
>                                                                                                 java_vm_ext.cc:591]   at void io.artmaker.export.DrawingManager.onDrawEvent(io.artmaker.actions.DrawEvent, int, int) (DrawingManager.kt:52)
>                                                                                                 java_vm_ext.cc:591]   at void io.artmaker.ArtMakerViewModel.onDrawEvent(io.artmaker.actions.DrawEvent) (ArtMakerViewModel.kt:89)`
> ```

It will crash because `pathlist` returns an empty list and we are calling `canErase` on  `computeUndoRedoState` only when pathList is NOT empty.  To be more specific check the conditional check on `MotionEvent.ActionMove`,  when `isEraserActive` is false, we are calling `updateCurrentShape` but when pathlist is Empty we don't need to `updateCurrentShape`. Thats why its crashing...

To fix this, check if `pathlist` is empty while updating currentShape, so we will have something like this on the drawing manager 
```
 private fun updateCurrentShape(offset: Offset, pressure: Float) {
       if (_pathList.isNotEmpty()){
           val idx = _pathList.lastIndex
           _pathList[idx].points.add(offset)
           _pathList[idx].alphas.add(pressure)
       }
    }
```

**Comment by emmanuelmuturia** [comment]
> > @Fbada006 @CalebKL I could use some help. In `ArtMaker.kt` from line 83 to 87 I try to dynamically toggle the Eraser once `state.canErase` switches to false but the app crashes just after it works. Please look into this and let me know how this could be fixed. Here is the referenced snippet and Stacktrace respectively:
> > `LaunchedEffect(key1 = state.canErase) { if (!state.canErase) { isEraserActive = false } }`
> > ```
> > `JNI DETECTED ERROR IN APPLICATION: JNI CallVoidMethodV called with pending exception java.lang.IndexOutOfBoundsException: index: -1, size: 0
> >                                                                                                 java_vm_ext.cc:591]   at void androidx.compose.runtime.external.kotlinx.collections.immutable.internal.ListImplementation.checkElementIndex$runtime_release(int, int) (ListImplementation.kt:15)
> >                                                                                                 java_vm_ext.cc:591]   at java.lang.Object androidx.compose.runtime.external.kotlinx.collections.immutable.implementations.immutableList.SmallPersistentVector.get(int) (SmallPersistentVector.kt:146)
> >                                                                                                 java_vm_ext.cc:591]   at java.lang.Object androidx.compose.runtime.snapshots.SnapshotStateList.get(int) (SnapshotStateList.kt:100)
> >                                                                                                 java_vm_ext.cc:591]   at void io.artmaker.export.DrawingManager.updateCurrentShape-3MmeM6k(long, float) (DrawingManager.kt:76)
> >                                                                                                 java_vm_ext.cc:591]   at void io.artmaker.export.DrawingManager.onDrawEvent(io.artmaker.actions.DrawEvent, int, int) (DrawingManager.kt:52)
> >                                                                                                 java_vm_ext.cc:591]   at void io.artmaker.ArtMakerViewModel.onDrawEvent(io.artmaker.actions.DrawEvent) (ArtMakerViewModel.kt:89)`
> > ```
> 
> It will crash because `pathlist` returns an empty list and we are calling `canErase` on `computeUndoRedoState` only when pathList is NOT empty. To be more specific check the conditional check on `MotionEvent.ActionMove`, when `isEraserActive` is false, we are calling `updateCurrentShape` but when pathlist is Empty we don't need to `updateCurrentShape`. Thats why its crashing...
> 
> To fix this, check if `pathlist` is empty while updating currentShape, so we will have something like this on the drawing manager
> 
> ```
>  private fun updateCurrentShape(offset: Offset, pressure: Float) {
>        if (_pathList.isNotEmpty()){
>            val idx = _pathList.lastIndex
>            _pathList[idx].points.add(offset)
>            _pathList[idx].alphas.add(pressure)
>        }
>     }
> ```

Thank you. It now works as expected. Feel free to review the rest of the latest changes...

**Review by CalebKL — APPROVED** [review]
LGTM

**Comment by Fbada006** [comment]
Hold on @emmanuelmuturia . Don't merge this. I will see if there is an alternative for the launched effect tomorrow.

**Comment by emmanuelmuturia** [comment]
> Hold on @emmanuelmuturia . Don't merge this. I will see if there is an alternative for the launched effect tomorrow.

No worries...

**Review by Fbada006 — DISMISSED** [review]
This is good. Nice work!

**Review by Fbada006 — APPROVED** [review]

**Pull request merged**
