### PR TITLE
Erasing Logic

### LINKED ISSUE #25: Add Rubbing functionality
When we draw, we should allow the user to be able to rub the art at any point on the canvas. The rub should be part of the controller icons as well.

### PR DESCRIPTION
**Pull request by emmanuelmuturia**
- Fixes #25 by adding the Erasing functionality...

### CODE REVIEW

**Review by CalebKL — CHANGES_REQUESTED** [review]
Hey, the way you have implementated the rubbing functionality is not right. You are drawing on top of another drawn points data with the background color of the canvas. In a way, the solution would mimic rubbing functionality but thats not correct. This means, when you rub, you are also drawing, so in the background there are alot of points data which we don't want. 
What we want to achieve is removing the points data that have already been drawn.

**Comment by emmanuelmuturia** [comment]
@CalebKL This is noted. Could you please point me to the right resources for Erasing on Canvas? I have searched for it and only got references to BlendMode which was clearing the whole drawing at once instead of continuously erasing the drawing. 

Also, will the Erase Circle be displayed upon touch either by finger or stylus? Will we also have to configure its size?

**Comment by CalebKL** [comment]
> @CalebKL This is noted. Could you please point me to the right resources for Erasing on Canvas? I have searched for it and only got references to BlendMode which was clearing the whole drawing at once instead of continuously erasing the drawing.
> 
> Also, will the Erase Circle be displayed upon touch either by finger or stylus? Will we also have to configure its size?

`_pathList` is mutable, so if we can add points data to it, it means, we can also remove data from it. Thats what I was thinking, Maybe try this and let me know if it would work.

**Comment by CalebKL** [comment]
@emmanuelmuturia I have tried running the app and its not rubbing any points, did you check if it was working?
Its actually drawing new points instead of rubbing.

**Comment by emmanuelmuturia** [comment]
> @emmanuelmuturia I have tried running the app and its not rubbing any points, did you check if it was working? Its actually drawing new points instead of rubbing.

The implementation still needs refining as I am redrawing the pathlist points that are not close to the Eraser radius. I tried removing the `_pathList` points as you suggested but the issue I was encountering was that the entire drawing was being removed instead of the individual points. What do you think I could do to improve my current implementation? Here is my current implementation's demo to confirm that my latest changes were working on my end:

[Erase.webm](https://github.com/user-attachments/assets/c4ffd3f3-ae1a-430f-9ebf-3425255f7c31)

**Comment by emmanuelmuturia** [comment]
@CalebKL Please let me know if it works now and what could be refined in my latest changes...

**Comment by Fbada006** [comment]
Closing this in favour of https://github.com/Fbada006/ArtMaker/pull/84

**Pull request closed without merging**
